"""
HWPX Generator - Claude XML → 한글 HWPX 변환기
================================================
Claude가 생성한 간단한 XML을 HWPX(한글 표준 문서) 포맷으로 변환합니다.

HWPX 구조:
  ├─ mimetype
  ├─ version.xml
  ├─ settings.xml
  ├─ META-INF/
  │   ├─ container.xml
  │   └─ manifest.xml
  ├─ Contents/
  │   ├─ content.hpf
  │   ├─ header.xml
  │   └─ section0.xml
  └─ Preview/
      └─ PrvText.txt
"""

import zipfile
import io
import xml.etree.ElementTree as ET
from xml.dom import minidom
from datetime import datetime
import re
import html


# ============================================================
# HWPX 내부 XML 템플릿
# ============================================================

MIMETYPE = "application/hwp+zip"

VERSION_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hv:HWPVersion xmlns:hv="urn:hancom:office:hwpml:version"
  version="1.1"
  application="Claude HWPX Generator"
  appVersion="1.0.0"
  os="Cross-Platform"
  osVersion="1.0"/>"""

SETTINGS_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hs:HWPApplicationSetting xmlns:hs="urn:hancom:office:hwpml:settings">
  <hs:CaretPosition list="0" para="0" pos="0"/>
</hs:HWPApplicationSetting>"""

CONTAINER_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0">
  <rootfiles>
    <rootfile full-path="Contents/content.hpf" media-type="application/hwp+zip"/>
  </rootfiles>
</container>"""

MANIFEST_XML = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0">
  <manifest:file-entry manifest:media-type="application/hwp+zip" manifest:full-path="/"/>
  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="Contents/content.hpf"/>
  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="Contents/header.xml"/>
  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="Contents/section0.xml"/>
  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="settings.xml"/>
  <manifest:file-entry manifest:media-type="text/xml" manifest:full-path="version.xml"/>
</manifest:manifest>"""


def make_content_hpf(title="문서", author="Claude"):
    """content.hpf - OPF 패키징 파일"""
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<opf:package xmlns:opf="http://www.idpf.org/2007/opf" version="1.0" unique-identifier="bookid">
  <opf:metadata>
    <opf:title>{html.escape(title)}</opf:title>
    <opf:language>ko</opf:language>
    <opf:meta name="creator" content="{html.escape(author)}"/>
    <opf:meta name="date" content="{now}"/>
    <opf:meta name="description" content="Generated by Claude HWPX Generator"/>
  </opf:metadata>
  <opf:manifest>
    <opf:item id="header" href="header.xml" media-type="text/xml"/>
    <opf:item id="section0" href="section0.xml" media-type="text/xml"/>
  </opf:manifest>
  <opf:spine>
    <opf:itemref idref="header"/>
    <opf:itemref idref="section0"/>
  </opf:spine>
</opf:package>"""


# ============================================================
# header.xml 생성 - 스타일 정의
# ============================================================

def make_header_xml():
    """header.xml - 문서 서식 정의 (폰트, 문단 모양 등)"""
    return """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hh:head xmlns:hh="urn:hancom:office:hwpml:head"
         xmlns:hp="urn:hancom:office:hwpml:paragraph"
         xmlns:ha="urn:hancom:office:hwpml:attr"
         version="1.1"
         secCnt="1">
  
  <!-- 매핑 테이블 -->
  <hh:mappingTable>
    
    <!-- 한글 폰트 -->
    <hh:faceNameList>
      <ha:fontface lang="HANGUL">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
        <ha:font id="1" face="함초롬바탕" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="LATIN">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
        <ha:font id="1" face="함초롬바탕" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="HANJA">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
        <ha:font id="1" face="함초롬바탕" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="JAPANESE">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="OTHER">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="SYMBOL">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
      </ha:fontface>
      <ha:fontface lang="USER">
        <ha:font id="0" face="함초롬돋움" type="TTF"/>
      </ha:fontface>
    </hh:faceNameList>
    
    <!-- 테두리/채우기 -->
    <hh:borderFillList>
      <!-- 기본 (투명) -->
      <ha:borderFill id="1" threeD="false" shadow="false" slash="0" backSlash="0" breakCellSeparateLine="0" centerLine="0">
        <ha:leftBorder type="NONE" width="0.12mm" color="#000000"/>
        <ha:rightBorder type="NONE" width="0.12mm" color="#000000"/>
        <ha:topBorder type="NONE" width="0.12mm" color="#000000"/>
        <ha:bottomBorder type="NONE" width="0.12mm" color="#000000"/>
        <ha:diagonal type="NONE" width="0.12mm" color="#000000"/>
      </ha:borderFill>
      <!-- 표 테두리용 -->
      <ha:borderFill id="2" threeD="false" shadow="false" slash="0" backSlash="0" breakCellSeparateLine="0" centerLine="0">
        <ha:leftBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:rightBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:topBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:bottomBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:diagonal type="NONE" width="0.12mm" color="#000000"/>
      </ha:borderFill>
      <!-- 표 헤더용 (회색 배경) -->
      <ha:borderFill id="3" threeD="false" shadow="false" slash="0" backSlash="0" breakCellSeparateLine="0" centerLine="0">
        <ha:leftBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:rightBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:topBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:bottomBorder type="SOLID" width="0.12mm" color="#000000"/>
        <ha:diagonal type="NONE" width="0.12mm" color="#000000"/>
        <ha:fillBrush>
          <ha:windowBrush faceColor="#D9E2F3" hatchColor="#FFFFFF" alpha="0"/>
        </ha:fillBrush>
      </ha:borderFill>
    </hh:borderFillList>

    <!-- 글자 모양 -->
    <hh:charPrList>
      <!-- 0: 본문 (10pt) -->
      <ha:charPr id="0" height="1000" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 1: 제목1 (22pt, Bold) -->
      <ha:charPr id="1" height="2200" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1" bold="true">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 2: 제목2 (16pt, Bold) -->
      <ha:charPr id="2" height="1600" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1" bold="true">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 3: 제목3 (13pt, Bold) -->
      <ha:charPr id="3" height="1300" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1" bold="true">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 4: Bold 본문 -->
      <ha:charPr id="4" height="1000" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1" bold="true">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 5: 표 본문 (9pt) -->
      <ha:charPr id="5" height="900" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
      <!-- 6: 표 헤더 (9pt, Bold) -->
      <ha:charPr id="6" height="900" textColor="#000000" shadeColor="none" useFontSpace="false" useKerning="false" symMark="NONE" borderFillIDRef="1" bold="true">
        <ha:fontRef hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:ratio hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:spacing hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
        <ha:relSz hangul="100" latin="100" hanja="100" japanese="100" other="100" symbol="100" user="100"/>
        <ha:offset hangul="0" latin="0" hanja="0" japanese="0" other="0" symbol="0" user="0"/>
      </ha:charPr>
    </hh:charPrList>

    <!-- 탭 -->
    <hh:tabPrList>
      <ha:tabPr id="0" autoTabLeft="false" autoTabRight="false"/>
    </hh:tabPrList>
    
    <!-- 번호 매기기 -->
    <hh:numberingList>
      <ha:numbering id="1" start="1">
        <ha:paraHead start="1" level="1" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="2" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="3" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="4" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="5" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="6" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
        <ha:paraHead start="1" level="7" align="LEFT" useInstWidth="true" autoIndent="true" widthAdjust="0" textOffsetType="PERCENT" textOffset="50" numFormat="DIGIT" charPrIDRef="0" checkable="false"/>
      </ha:numbering>
    </hh:numberingList>

    <!-- 글머리 기호 -->
    <hh:bulletList>
      <ha:bullet id="1" char="●"/>
    </hh:bulletList>

    <!-- 문단 모양 -->
    <hh:paraPrList>
      <!-- 0: 본문 -->
      <ha:paraPr id="0" align="JUSTIFY" verAlign="BASELINE" heading="NONE" level="0" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="false" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="0" left="0" right="0"/>
        <ha:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/>
        <ha:spacing before="0" after="0"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
      <!-- 1: 제목1 -->
      <ha:paraPr id="1" align="LEFT" verAlign="BASELINE" heading="OUTLINE" level="0" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="true" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="0" left="0" right="0"/>
        <ha:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/>
        <ha:spacing before="400" after="200"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
      <!-- 2: 제목2 -->
      <ha:paraPr id="2" align="LEFT" verAlign="BASELINE" heading="OUTLINE" level="1" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="true" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="0" left="0" right="0"/>
        <ha:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/>
        <ha:spacing before="300" after="150"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
      <!-- 3: 제목3 -->
      <ha:paraPr id="3" align="LEFT" verAlign="BASELINE" heading="OUTLINE" level="2" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="true" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="0" left="0" right="0"/>
        <ha:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/>
        <ha:spacing before="200" after="100"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
      <!-- 4: 표 내부 문단 -->
      <ha:paraPr id="4" align="CENTER" verAlign="BASELINE" heading="NONE" level="0" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="false" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="0" left="0" right="0"/>
        <ha:lineSpacing type="PERCENT" value="150" unit="HWPUNIT"/>
        <ha:spacing before="0" after="0"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
      <!-- 5: 리스트 문단 -->
      <ha:paraPr id="5" align="JUSTIFY" verAlign="BASELINE" heading="NONE" level="0" tabPrIDRef="0" breakLatinWord="KEEP_WORD" breakNonLatinWord="true" snapToGrid="true" condense="0" widowOrphan="false" keepWithNext="false" keepLines="false" pageBreakBefore="false" fontLineHeight="false" lineWrap="BREAK" autoSpaceEAsianEng="true" autoSpaceEAsianNum="true">
        <ha:margin indent="-300" left="600" right="0"/>
        <ha:lineSpacing type="PERCENT" value="160" unit="HWPUNIT"/>
        <ha:spacing before="0" after="0"/>
        <ha:border borderFillIDRef="1" offsetLeft="0" offsetRight="0" offsetTop="0" offsetBottom="0" connect="false" ignoreMargin="false"/>
      </ha:paraPr>
    </hh:paraPrList>

    <!-- 스타일 -->
    <hh:styleList>
      <ha:style id="0" type="PARA" name="본문" engName="Body" paraPrIDRef="0" charPrIDRef="0" nextStyleIDRef="0"/>
      <ha:style id="1" type="PARA" name="제목 1" engName="Heading 1" paraPrIDRef="1" charPrIDRef="1" nextStyleIDRef="0"/>
      <ha:style id="2" type="PARA" name="제목 2" engName="Heading 2" paraPrIDRef="2" charPrIDRef="2" nextStyleIDRef="0"/>
      <ha:style id="3" type="PARA" name="제목 3" engName="Heading 3" paraPrIDRef="3" charPrIDRef="3" nextStyleIDRef="0"/>
    </hh:styleList>

  </hh:mappingTable>

  <!-- 호환 문서 -->
  <hh:compatibleDocument/>
  
  <!-- 문서 설정 -->
  <hh:docOption>
    <hh:linkinfo/>
  </hh:docOption>

</hh:head>"""


# ============================================================
# section0.xml 생성 - 본문 콘텐츠 변환
# ============================================================

# 용지 기본 설정 (A4 기준, HWPUNIT: 1/7200 inch → mm 환산)
# A4: 210mm x 297mm → HWPUNIT: 59528 x 84188
PAGE_WIDTH = 59528
PAGE_HEIGHT = 84188
MARGIN_LEFT = 8504    # ~30mm
MARGIN_RIGHT = 8504
MARGIN_TOP = 5668     # ~20mm  
MARGIN_BOTTOM = 4252  # ~15mm
MARGIN_HEADER = 4252
MARGIN_FOOTER = 4252


def _escape_xml(text):
    """XML 특수문자 이스케이프"""
    if text is None:
        return ""
    return html.escape(str(text))


def _make_paragraph(text, char_pr_id="0", para_pr_id="0", style_id="0"):
    """단일 문단 XML 생성"""
    escaped = _escape_xml(text)
    return f"""<hp:p paraPrIDRef="{para_pr_id}" styleIDRef="{style_id}">
      <hp:run charPrIDRef="{char_pr_id}">
        <hp:t>{escaped}</hp:t>
      </hp:run>
    </hp:p>"""


def _make_table_cell(text, is_header=False, col_width=10000):
    """표 셀 XML 생성"""
    char_pr = "6" if is_header else "5"
    border_fill = "3" if is_header else "2"
    escaped = _escape_xml(text)
    return f"""<hp:tc borderFillIDRef="{border_fill}">
            <hp:cellAddr colAddr="0" rowAddr="0"/>
            <hp:cellSpan colSpan="1" rowSpan="1"/>
            <hp:cellSz width="{col_width}" height="1000"/>
            <hp:cellMargin left="170" right="170" top="85" bottom="85"/>
            <hp:subList>
              <hp:p paraPrIDRef="4" styleIDRef="0">
                <hp:run charPrIDRef="{char_pr}">
                  <hp:t>{escaped}</hp:t>
                </hp:run>
              </hp:p>
            </hp:subList>
          </hp:tc>"""


def parse_claude_xml(xml_string):
    """Claude가 생성한 간단한 XML을 파싱하여 HWPX section XML로 변환"""
    
    # XML 파싱
    try:
        root = ET.fromstring(xml_string)
    except ET.ParseError as e:
        raise ValueError(f"XML 파싱 오류: {e}")
    
    paragraphs = []
    preview_texts = []
    
    for elem in root:
        tag = elem.tag.lower()
        
        # ---- 제목 (heading) ----
        if tag == "heading":
            level = elem.get("level", "1")
            text = (elem.text or "").strip()
            preview_texts.append(text)
            
            if level == "1":
                paragraphs.append(_make_paragraph(text, char_pr_id="1", para_pr_id="1", style_id="1"))
            elif level == "2":
                paragraphs.append(_make_paragraph(text, char_pr_id="2", para_pr_id="2", style_id="2"))
            elif level == "3":
                paragraphs.append(_make_paragraph(text, char_pr_id="3", para_pr_id="3", style_id="3"))
            else:
                paragraphs.append(_make_paragraph(text, char_pr_id="3", para_pr_id="3", style_id="3"))
        
        # ---- 문단 (paragraph / p) ----
        elif tag in ("paragraph", "p"):
            text = (elem.text or "").strip()
            # 하위 요소에서 텍스트 조합
            if len(elem) > 0:
                parts = []
                if elem.text:
                    parts.append(elem.text)
                for child in elem:
                    if child.text:
                        parts.append(child.text)
                    if child.tail:
                        parts.append(child.tail)
                text = "".join(parts).strip()
            
            preview_texts.append(text)
            is_bold = elem.get("bold", "").lower() == "true"
            char_pr = "4" if is_bold else "0"
            paragraphs.append(_make_paragraph(text, char_pr_id=char_pr, para_pr_id="0", style_id="0"))
        
        # ---- 표 (table) ----
        elif tag == "table":
            rows_elems = elem.findall("row")
            if not rows_elems:
                rows_elems = elem.findall("tr")
            
            if not rows_elems:
                continue
                
            # 열 개수 파악
            first_row = rows_elems[0]
            cells_in_first = first_row.findall("cell")
            if not cells_in_first:
                cells_in_first = first_row.findall("td")
            if not cells_in_first:
                cells_in_first = first_row.findall("th")
            col_count = len(cells_in_first)
            if col_count == 0:
                continue
            
            # 사용 가능한 너비 계산
            usable_width = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT
            col_width = usable_width // col_count
            
            has_header = elem.get("header", "").lower() == "true" or \
                         first_row.findall("th") or \
                         elem.get("has_header", "").lower() == "true"
            
            # 표 XML 생성
            table_rows_xml = []
            for row_idx, row_elem in enumerate(rows_elems):
                cells = row_elem.findall("cell")
                if not cells:
                    cells = row_elem.findall("td")
                if not cells:
                    cells = row_elem.findall("th")
                    
                is_header_row = (row_idx == 0 and has_header) or bool(row_elem.findall("th"))
                
                cells_xml = []
                for cell_elem in cells:
                    cell_text = (cell_elem.text or "").strip()
                    if len(cell_elem) > 0:
                        parts = []
                        if cell_elem.text:
                            parts.append(cell_elem.text)
                        for child in cell_elem:
                            if child.text:
                                parts.append(child.text)
                            if child.tail:
                                parts.append(child.tail)
                        cell_text = "".join(parts).strip()
                    
                    preview_texts.append(cell_text)
                    cells_xml.append(_make_table_cell(cell_text, is_header=is_header_row, col_width=col_width))
                
                table_rows_xml.append(f"""        <hp:tr>
          {"".join(cells_xml)}
        </hp:tr>""")
            
            table_xml = f"""<hp:p paraPrIDRef="0" styleIDRef="0">
      <hp:ctrl>
        <hp:tbl colCnt="{col_count}" rowCnt="{len(rows_elems)}" cellSpacing="0" borderFillIDRef="2">
          <hp:inMargin left="170" right="170" top="85" bottom="85"/>
{"".join(table_rows_xml)}
        </hp:tbl>
      </hp:ctrl>
    </hp:p>"""
            paragraphs.append(table_xml)
        
        # ---- 리스트 (list / ul / ol) ----
        elif tag in ("list", "ul", "ol"):
            is_ordered = tag == "ol" or elem.get("type", "").lower() == "ordered"
            items = elem.findall("item")
            if not items:
                items = elem.findall("li")
            
            for idx, item_elem in enumerate(items):
                item_text = (item_elem.text or "").strip()
                preview_texts.append(item_text)
                
                if is_ordered:
                    prefix = f"{idx + 1}. "
                else:
                    prefix = "● "
                
                paragraphs.append(_make_paragraph(f"{prefix}{item_text}", char_pr_id="0", para_pr_id="5", style_id="0"))
        
        # ---- 빈 줄 (br / blank) ----
        elif tag in ("br", "blank", "newline"):
            paragraphs.append(_make_paragraph("", char_pr_id="0", para_pr_id="0", style_id="0"))
        
        # ---- 수평선 (hr) ----
        elif tag == "hr":
            paragraphs.append(_make_paragraph("─" * 40, char_pr_id="0", para_pr_id="0", style_id="0"))
    
    return paragraphs, preview_texts


def make_section_xml(paragraphs):
    """section0.xml 전체 생성"""
    body = "\n    ".join(paragraphs)
    
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hs:sec xmlns:hp="urn:hancom:office:hwpml:paragraph"
        xmlns:hs="urn:hancom:office:hwpml:section"
        xmlns:ha="urn:hancom:office:hwpml:attr">
  <hp:secPr textDirection="HORIZONTAL" spaceColumns="1134" tabStop="8000" outlineShapeIDRef="1" memoShapeIDRef="0" textVerticalWidthHead="0">
    <hp:pagePr landscape="NARROWLY" width="{PAGE_WIDTH}" height="{PAGE_HEIGHT}" gutterType="LEFT_ONLY">
      <hp:margin header="{MARGIN_HEADER}" footer="{MARGIN_FOOTER}" left="{MARGIN_LEFT}" right="{MARGIN_RIGHT}" top="{MARGIN_TOP}" bottom="{MARGIN_BOTTOM}" gutter="0"/>
    </hp:pagePr>
    <hp:footNotePr>
      <hp:autoNumFormat type="DIGIT" suffixChar=")" superscript="false"/>
      <hp:noteLine length="-1" type="SOLID" width="0.12mm" color="#000000"/>
      <hp:noteSpacing betweenNotes="283" belowLine="567" aboveLine="850"/>
      <hp:numbering type="CONTINUOUS" newNum="1"/>
      <hp:placement type="EACH_COLUMN" beneathText="false"/>
    </hp:footNotePr>
    <hp:endNotePr>
      <hp:autoNumFormat type="DIGIT" suffixChar=")" superscript="false"/>
      <hp:noteLine length="0" type="SOLID" width="0.12mm" color="#000000"/>
      <hp:noteSpacing betweenNotes="0" belowLine="567" aboveLine="850"/>
      <hp:numbering type="CONTINUOUS" newNum="1"/>
      <hp:placement type="END_OF_DOCUMENT" beneathText="false"/>
    </hp:endNotePr>
  </hp:secPr>
    {body}
</hs:sec>"""


# ============================================================
# HWPX 파일 생성
# ============================================================

def generate_hwpx(xml_string, title="문서", author="Claude"):
    """
    Claude XML → HWPX 파일 생성
    
    Args:
        xml_string: Claude가 생성한 XML 문자열
        title: 문서 제목
        author: 작성자
    
    Returns:
        bytes: HWPX 파일 바이너리 데이터
    """
    # 파싱
    paragraphs, preview_texts = parse_claude_xml(xml_string)
    
    if not paragraphs:
        # 빈 문서라도 하나의 빈 문단 추가
        paragraphs.append(_make_paragraph(""))
    
    # HWPX ZIP 생성
    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # mimetype은 압축하지 않음 (ZIP 규격)
        zf.writestr("mimetype", MIMETYPE, compress_type=zipfile.ZIP_STORED)
        
        # 메타 파일들
        zf.writestr("version.xml", VERSION_XML)
        zf.writestr("settings.xml", SETTINGS_XML)
        
        # META-INF
        zf.writestr("META-INF/container.xml", CONTAINER_XML)
        zf.writestr("META-INF/manifest.xml", MANIFEST_XML)
        
        # Contents
        zf.writestr("Contents/content.hpf", make_content_hpf(title, author))
        zf.writestr("Contents/header.xml", make_header_xml())
        zf.writestr("Contents/section0.xml", make_section_xml(paragraphs))
        
        # Preview
        preview_text = "\n".join(preview_texts[:50])  # 미리보기는 50줄까지
        zf.writestr("Preview/PrvText.txt", preview_text)
    
    buffer.seek(0)
    return buffer.getvalue()


# ============================================================
# Claude XML 스키마 정의 (가이드)
# ============================================================

CLAUDE_XML_SCHEMA = """
╔══════════════════════════════════════════════════════════════╗
║          Claude XML → HWPX 변환 스키마 가이드               ║
╚══════════════════════════════════════════════════════════════╝

<document title="문서 제목" author="작성자">

  <!-- 제목 (level: 1, 2, 3) -->
  <heading level="1">대제목</heading>
  <heading level="2">중제목</heading>
  <heading level="3">소제목</heading>

  <!-- 본문 문단 -->
  <paragraph>일반 본문 텍스트입니다.</paragraph>
  <paragraph bold="true">굵은 본문 텍스트입니다.</paragraph>
  <!-- 또는 줄임형 -->
  <p>짧은 문단</p>
  
  <!-- 빈 줄 -->
  <br/>

  <!-- 수평선 -->
  <hr/>

  <!-- 표 (첫 행을 헤더로 처리하려면 header="true" 또는 <th> 사용) -->
  <table header="true">
    <row>
      <cell>헤더1</cell>
      <cell>헤더2</cell>
      <cell>헤더3</cell>
    </row>
    <row>
      <cell>데이터1</cell>
      <cell>데이터2</cell>
      <cell>데이터3</cell>
    </row>
  </table>

  <!-- 순서 없는 목록 -->
  <list>
    <item>항목 1</item>
    <item>항목 2</item>
  </list>

  <!-- 순서 있는 목록 -->
  <list type="ordered">
    <item>첫 번째</item>
    <item>두 번째</item>
  </list>

  <!-- HTML 스타일도 지원 -->
  <ol>
    <li>항목 A</li>
    <li>항목 B</li>
  </ol>
  <ul>
    <li>불릿 A</li>
    <li>불릿 B</li>
  </ul>

</document>
"""


if __name__ == "__main__":
    # 테스트
    test_xml = """<document title="테스트 문서" author="Claude">
    <heading level="1">AI 중심대학 추진 현황</heading>
    <paragraph>차의과학대학교는 Bio Healthcare AI 특화 전략을 추진하고 있습니다.</paragraph>
    <heading level="2">주요 성과지표</heading>
    <table header="true">
        <row><cell>구분</cell><cell>현재</cell><cell>목표</cell></row>
        <row><cell>AI 교과비율</cell><cell>5.7%</cell><cell>20%</cell></row>
        <row><cell>AI 교원수</cell><cell>37명</cell><cell>50명</cell></row>
        <row><cell>AI Ambassador</cell><cell>11명</cell><cell>20명</cell></row>
    </table>
    <heading level="2">추진 방향</heading>
    <list>
        <item>AI 교육과정 개편 및 확대</item>
        <item>산학협력 기반 연구 프로젝트 추진</item>
        <item>글로벌 네트워크 강화</item>
    </list>
    <paragraph>향후 8개년에 걸쳐 체계적으로 추진할 예정입니다.</paragraph>
</document>"""
    
    hwpx_data = generate_hwpx(test_xml, title="테스트 문서", author="Claude")
    
    with open("/home/claude/test_output.hwpx", "wb") as f:
        f.write(hwpx_data)
    
    print(f"✅ HWPX 파일 생성 완료: {len(hwpx_data):,} bytes")
    print(CLAUDE_XML_SCHEMA)
